// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rueuhdjpvamlwgoavyti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1ZXVoZGpwdmFtbHdnb2F2eXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzI0NzYsImV4cCI6MjA2ODE0ODQ3Nn0._8dFsXX6kDziiPeZOhI_VQpzy-2acP6_hGBjj-Zzepk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});